### ISSUE TITLE
Fitur Pra-Bencana (Read Persiapan di dalam rumah)

### ISSUE THREAD

**Issue by RHEFAR** [adeliarnur/magazine#1]
FEATURE
**OPEN PERSIAPAN   DIDALAM RUMAH SECTION**

SCENARIO
**OPEN PERSIAPAN   DIDALAM RUMAH SECTION**

PRECONDITION
- **GIVEN** ANOTHER SECTION   INTERFACE

ACTION
- **WHEN**   USER SELECT “MATERI” IN NAVBAR
- **AND**   SELECT   ”PRA BENCANA” SUB-SECTION
- **AND**   THEN SELECT   ”PERSIAPAN DIDALAM RUMAH”

OUTCOME
- **THEN** USER IS MOVED TO   THE INFORMATION OF A GUIDE TO MINIMIZING AN IMPACT FROM DISASTER WHICH HAVE   BEEN SELECTED

**Comment by RHEFAR** [comment]
kenapa belum di close? tapi sudah done

**Comment by Alvinnurraihan** [comment]
belum selesai untuk input datanya

**Comment by Alvinnurraihan** [comment]
kira kira selesainya maksimal sabtu

**Comment by Alvinnurraihan** [comment]
update: sudah selesai update data, hanya tinggal update header saja, ada sedikit perubahan
