### ISSUE TITLE
Fitur Pra-Bencana (Read Persiapan Diri)

### ISSUE THREAD

**Issue by RHEFAR** [adeliarnur/magazine#3]
FEATURE
**OPEN PERSIAPAN   DIRI SECTION**

SCENARIO
**OPEN PERSIAPAN   DIRI SECTION**

PRECONDITION
- **GIVEN** ANOTHER SECTION   INTERFACE

ACTION
- **WHEN**   USER SELECT “MATERI” IN NAVBAR
- **AND**   SELECT   ”PRA BENCANA” SUB-SECTION
- **AND**   THEN SELECT   ”PERSIAPAN DIRI”

OUTCOME
- **THEN** USER IS MOVED TO   THE INFORMATION OF A GUIDE TO MINIMIZING AN IMPACT FROM DISASTER WHICH HAVE   BEEN SELECTED

**Comment by RHEFAR** [comment]
ini kenapa belum di close juga?

**Comment by Alvinnurraihan** [comment]
untuk input data belum selesai, maksimal hari sabtu ( Sama dengan persiapan di dalam rumah)

**Comment by Alvinnurraihan** [comment]
update: sudah selesai update data, hanya tinggal update header saja, ada sedikit perubahan
