### ISSUE TITLE
LOGIN Admin

### ISSUE THREAD

**Issue by RHEFAR** [adeliarnur/magazine#5]
FEATURE
**LOGIN ADMIN** 

SCENARIO
**OPEN LOGIN ADMIN PAGE**

PRECONDITION
**GIVEN** FORM LOGIN ADMIN

ACTION

- **WHEN** ADMIN INPUT USERNAME
- **AND** INPUT PASSWORD
- **AND** CLICK “LOG IN”

OUTCOME
**THEN** ADMIN IS MOVED TO ADMIN PAGE SECTION

**Comment by syakirali** [comment]
Sudah dibuatkan fitur loginnya beserta implementasi cek autentikasinya.
Setiap fitur yang mengharuskan login, diharuskan menambahkan kode berikut di kode paling awal/teratas.

`include_once 'includes/authentication.php';`
`id_role_harus([1]);`

fungsi **id_role_harus()** membutuhkan parameter berupa array id_role, yang mana hanya terdapat 2 role, yaitu
id **1** untuk role Admin Non LSM
id **2** untuk role Admin LSM
_*lebih lengkap mengenai role bisa dilihat di database `users_role`_

Dalam contoh di atas, role yang diperbolehkan mengakses hanyalah role admin Non LSM saja.

Jika fitur dapat diakses oleh admin LSM dan non LSM, maka kode yang disisipkan adalah
`include_once 'includes/authentication.php';`
`id_role_harus([1,2]);`
